server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import:
      - optional:file:./env/db.env.properties
      - optional:file:./.env.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver